add_test( can_output_test.result_true /mnt/c/Users/16078/Desktop/CampusNavigation/build/test/CampusNavigation_test [==[--gtest_filter=can_output_test.result_true]==] --gtest_also_run_disabled_tests)
set_tests_properties( can_output_test.result_true PROPERTIES WORKING_DIRECTORY /mnt/c/Users/16078/Desktop/CampusNavigation/build/test)
add_test( can_output_test.result_false /mnt/c/Users/16078/Desktop/CampusNavigation/build/test/CampusNavigation_test [==[--gtest_filter=can_output_test.result_false]==] --gtest_also_run_disabled_tests)
set_tests_properties( can_output_test.result_false PROPERTIES WORKING_DIRECTORY /mnt/c/Users/16078/Desktop/CampusNavigation/build/test)
add_test( nav.nav_test /mnt/c/Users/16078/Desktop/CampusNavigation/build/test/CampusNavigation_test [==[--gtest_filter=nav.nav_test]==] --gtest_also_run_disabled_tests)
set_tests_properties( nav.nav_test PROPERTIES WORKING_DIRECTORY /mnt/c/Users/16078/Desktop/CampusNavigation/build/test)
add_test( Env.modelhub_building_test /mnt/c/Users/16078/Desktop/CampusNavigation/build/test/CampusNavigation_test [==[--gtest_filter=Env.modelhub_building_test]==] --gtest_also_run_disabled_tests)
set_tests_properties( Env.modelhub_building_test PROPERTIES WORKING_DIRECTORY /mnt/c/Users/16078/Desktop/CampusNavigation/build/test)
add_test( Env.modelhub_path_test /mnt/c/Users/16078/Desktop/CampusNavigation/build/test/CampusNavigation_test [==[--gtest_filter=Env.modelhub_path_test]==] --gtest_also_run_disabled_tests)
set_tests_properties( Env.modelhub_path_test PROPERTIES WORKING_DIRECTORY /mnt/c/Users/16078/Desktop/CampusNavigation/build/test)
add_test( Env.connection_test /mnt/c/Users/16078/Desktop/CampusNavigation/build/test/CampusNavigation_test [==[--gtest_filter=Env.connection_test]==] --gtest_also_run_disabled_tests)
set_tests_properties( Env.connection_test PROPERTIES WORKING_DIRECTORY /mnt/c/Users/16078/Desktop/CampusNavigation/build/test)
add_test( Env.invalid_id_exception_test /mnt/c/Users/16078/Desktop/CampusNavigation/build/test/CampusNavigation_test [==[--gtest_filter=Env.invalid_id_exception_test]==] --gtest_also_run_disabled_tests)
set_tests_properties( Env.invalid_id_exception_test PROPERTIES WORKING_DIRECTORY /mnt/c/Users/16078/Desktop/CampusNavigation/build/test)
add_test( system_time.format_test /mnt/c/Users/16078/Desktop/CampusNavigation/build/test/CampusNavigation_test [==[--gtest_filter=system_time.format_test]==] --gtest_also_run_disabled_tests)
set_tests_properties( system_time.format_test PROPERTIES WORKING_DIRECTORY /mnt/c/Users/16078/Desktop/CampusNavigation/build/test)
set( CampusNavigation_test_TESTS can_output_test.result_true can_output_test.result_false nav.nav_test Env.modelhub_building_test Env.modelhub_path_test Env.connection_test Env.invalid_id_exception_test system_time.format_test)
