name: Campus Navigation CI

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - master
jobs:
    build-and-test:
        name: Building and testing the cmake project
        runs-on: ubuntu-latest
        steps:
            - name: Install boost
              run: sudo apt-get update && sudo apt-get install -yq libboost1.72-dev
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: CMake setup
              run: |
                  mkdir build
                  cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
            - name: Make the Project
              run: |
                  cd build && make -j2
            - name: Run unit tests
              run: |
                  cd build && test/CampusNavigation_test
