name: Campus Navigation CI

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - master
jobs:
    build-and-test:
        name: Building and testing the cmake project
        runs-on: ubuntu-latest
        steps:
            - name: Install boost
              uses: MarkusJx/install-boost@v1.0.1
              id: install-boost
              with:
                  boost_version: 1.73.0
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: CMake setup
              run: |
                  mkdir build
                  cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
                  env:
                    BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
            - name: Make the Project
              run: |
                  cd build && make -j2
            - name: Run unit tests
              run: |
                  cd build && test/CampusNavigation_test
